### PR TITLE
Add support for /proc/net/dev, /proc/[pid]/net/dev, and /proc/[pid]/ns

### PR DESCRIPTION
**Pull request by andrewkroh**
`/proc/net/dev` and `/proc/[pid]/net/dev` provide network interface metrics. These are the values that ifconfig reads.

`/proc/[pid]/ns` is directory containing symlinks that describe what namespaces the process is a member of.

### CODE REVIEW

**Comment by monicasarbu** [comment]
Nice @andrewkroh

**Comment by ruflin** [comment]
@andrewkroh we should add a CHANGELOG.md to the repo and add travis that at least does the `go fmt` and `go test`.

**Comment by andrewkroh** [comment]
@ruflin With the barebones .travis.yml in the project it actually does both a `go fmt` check and a `go test`. I was surprised too.

**Comment by ruflin** [comment]
@andrewkroh oh, yes that is a surprise :-) Travis magic.

**Pull request merged**
